# Generated by Django 4.2.6 on 2023-11-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_country_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_subscription',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата Подписки'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.BooleanField(default=False, verbose_name='Подписка на сервис'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верификация'),
        ),
    ]
