# Generated by Django 4.2.6 on 2023-11-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_date_of_subscription_user_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код доступа'),
        ),
    ]
