# Generated by Django 4.2.6 on 2023-11-10 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_amount', models.IntegerField(verbose_name='сумма оплаты')),
                ('is_paid', models.BooleanField(default=False, verbose_name='статус оплаты')),
                ('session', models.CharField(blank=True, max_length=180, null=True, verbose_name='сессия для оплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-date_of_payment',),
            },
        ),
    ]
