# Generated by Django 4.2.6 on 2023-11-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_payment_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='id платежа'),
        ),
    ]
