# Generated by Django 4.2.6 on 2023-11-03 00:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name=' Человекопонятный URL')),
                ('date_of_create', models.DateTimeField(verbose_name='Дата создания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/img/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, null=True, upload_to='publications/video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Видео')),
                ('sign_of_publication', models.BooleanField(blank=True, default=True, null=True, verbose_name='Признак публикации')),
                ('quantity_of_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ('header',),
            },
        ),
    ]
