# Generated by Django 4.2.6 on 2023-11-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publication_date_of_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Признак платной публикации'),
        ),
    ]
